version: '2'
services:
  weibo:
    image: registry.cn-hangzhou.aliyuncs.com/wangxiangtest/app-weibo:v1.0.0
    env_file: "./app-weibo.env"
  cron:
    image: registry.cn-hangzhou.aliyuncs.com/wangxiangtest/app-weibo:v1.0.0
    env_file: "./app-weibo.env"
    command: ['cron', '-f']
  worker:
    image: registry.cn-hangzhou.aliyuncs.com/wangxiangtest/app-weibo:v1.0.0
    env_file: "./app-weibo.env"
    command: ['/usr/bin/supervisord', '-n', '-c', '/etc/supervisor/supervisord.conf']
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/wangxiangtest/app-nginx:v1.0.0
    volumes_from:
      - weibo
    depends_on:
      - weibo
    ports:
      - "8888:80"